// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: github.com/openconfig/ovgs/ovgs.proto

package ovgs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OwnershipVoucherService_CreateGroup_FullMethodName         = "/ovgs.v1.OwnershipVoucherService/CreateGroup"
	OwnershipVoucherService_DeleteGroup_FullMethodName         = "/ovgs.v1.OwnershipVoucherService/DeleteGroup"
	OwnershipVoucherService_GetGroup_FullMethodName            = "/ovgs.v1.OwnershipVoucherService/GetGroup"
	OwnershipVoucherService_AddUserRole_FullMethodName         = "/ovgs.v1.OwnershipVoucherService/AddUserRole"
	OwnershipVoucherService_RemoveUserRole_FullMethodName      = "/ovgs.v1.OwnershipVoucherService/RemoveUserRole"
	OwnershipVoucherService_GetUserRole_FullMethodName         = "/ovgs.v1.OwnershipVoucherService/GetUserRole"
	OwnershipVoucherService_AddSerial_FullMethodName           = "/ovgs.v1.OwnershipVoucherService/AddSerial"
	OwnershipVoucherService_RemoveSerial_FullMethodName        = "/ovgs.v1.OwnershipVoucherService/RemoveSerial"
	OwnershipVoucherService_GetSerial_FullMethodName           = "/ovgs.v1.OwnershipVoucherService/GetSerial"
	OwnershipVoucherService_CreateDomainCert_FullMethodName    = "/ovgs.v1.OwnershipVoucherService/CreateDomainCert"
	OwnershipVoucherService_DeleteDomainCert_FullMethodName    = "/ovgs.v1.OwnershipVoucherService/DeleteDomainCert"
	OwnershipVoucherService_GetDomainCert_FullMethodName       = "/ovgs.v1.OwnershipVoucherService/GetDomainCert"
	OwnershipVoucherService_GetOwnershipVoucher_FullMethodName = "/ovgs.v1.OwnershipVoucherService/GetOwnershipVoucher"
)

// OwnershipVoucherServiceClient is the client API for OwnershipVoucherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OwnershipVoucherServiceClient interface {
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	AddUserRole(ctx context.Context, in *AddUserRoleRequest, opts ...grpc.CallOption) (*AddUserRoleResponse, error)
	RemoveUserRole(ctx context.Context, in *RemoveUserRoleRequest, opts ...grpc.CallOption) (*RemoveUserRoleResponse, error)
	GetUserRole(ctx context.Context, in *GetUserRoleRequest, opts ...grpc.CallOption) (*GetUserRoleResponse, error)
	AddSerial(ctx context.Context, in *AddSerialRequest, opts ...grpc.CallOption) (*AddSerialResponse, error)
	RemoveSerial(ctx context.Context, in *RemoveSerialRequest, opts ...grpc.CallOption) (*RemoveSerialResponse, error)
	GetSerial(ctx context.Context, in *GetSerialRequest, opts ...grpc.CallOption) (*GetSerialResponse, error)
	CreateDomainCert(ctx context.Context, in *CreateDomainCertRequest, opts ...grpc.CallOption) (*CreateDomainCertResponse, error)
	DeleteDomainCert(ctx context.Context, in *DeleteDomainCertRequest, opts ...grpc.CallOption) (*DeleteDomainCertResponse, error)
	GetDomainCert(ctx context.Context, in *GetDomainCertRequest, opts ...grpc.CallOption) (*GetDomainCertResponse, error)
	GetOwnershipVoucher(ctx context.Context, in *GetOwnershipVoucherRequest, opts ...grpc.CallOption) (*GetOwnershipVoucherResponse, error)
}

type ownershipVoucherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOwnershipVoucherServiceClient(cc grpc.ClientConnInterface) OwnershipVoucherServiceClient {
	return &ownershipVoucherServiceClient{cc}
}

func (c *ownershipVoucherServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGroupResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) AddUserRole(ctx context.Context, in *AddUserRoleRequest, opts ...grpc.CallOption) (*AddUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserRoleResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_AddUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) RemoveUserRole(ctx context.Context, in *RemoveUserRoleRequest, opts ...grpc.CallOption) (*RemoveUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserRoleResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_RemoveUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) GetUserRole(ctx context.Context, in *GetUserRoleRequest, opts ...grpc.CallOption) (*GetUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRoleResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_GetUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) AddSerial(ctx context.Context, in *AddSerialRequest, opts ...grpc.CallOption) (*AddSerialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSerialResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_AddSerial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) RemoveSerial(ctx context.Context, in *RemoveSerialRequest, opts ...grpc.CallOption) (*RemoveSerialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSerialResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_RemoveSerial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) GetSerial(ctx context.Context, in *GetSerialRequest, opts ...grpc.CallOption) (*GetSerialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSerialResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_GetSerial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) CreateDomainCert(ctx context.Context, in *CreateDomainCertRequest, opts ...grpc.CallOption) (*CreateDomainCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDomainCertResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_CreateDomainCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) DeleteDomainCert(ctx context.Context, in *DeleteDomainCertRequest, opts ...grpc.CallOption) (*DeleteDomainCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDomainCertResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_DeleteDomainCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) GetDomainCert(ctx context.Context, in *GetDomainCertRequest, opts ...grpc.CallOption) (*GetDomainCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDomainCertResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_GetDomainCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ownershipVoucherServiceClient) GetOwnershipVoucher(ctx context.Context, in *GetOwnershipVoucherRequest, opts ...grpc.CallOption) (*GetOwnershipVoucherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOwnershipVoucherResponse)
	err := c.cc.Invoke(ctx, OwnershipVoucherService_GetOwnershipVoucher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OwnershipVoucherServiceServer is the server API for OwnershipVoucherService service.
// All implementations should embed UnimplementedOwnershipVoucherServiceServer
// for forward compatibility.
type OwnershipVoucherServiceServer interface {
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	AddUserRole(context.Context, *AddUserRoleRequest) (*AddUserRoleResponse, error)
	RemoveUserRole(context.Context, *RemoveUserRoleRequest) (*RemoveUserRoleResponse, error)
	GetUserRole(context.Context, *GetUserRoleRequest) (*GetUserRoleResponse, error)
	AddSerial(context.Context, *AddSerialRequest) (*AddSerialResponse, error)
	RemoveSerial(context.Context, *RemoveSerialRequest) (*RemoveSerialResponse, error)
	GetSerial(context.Context, *GetSerialRequest) (*GetSerialResponse, error)
	CreateDomainCert(context.Context, *CreateDomainCertRequest) (*CreateDomainCertResponse, error)
	DeleteDomainCert(context.Context, *DeleteDomainCertRequest) (*DeleteDomainCertResponse, error)
	GetDomainCert(context.Context, *GetDomainCertRequest) (*GetDomainCertResponse, error)
	GetOwnershipVoucher(context.Context, *GetOwnershipVoucherRequest) (*GetOwnershipVoucherResponse, error)
}

// UnimplementedOwnershipVoucherServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOwnershipVoucherServiceServer struct{}

func (UnimplementedOwnershipVoucherServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) AddUserRole(context.Context, *AddUserRoleRequest) (*AddUserRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserRole not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) RemoveUserRole(context.Context, *RemoveUserRoleRequest) (*RemoveUserRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserRole not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) GetUserRole(context.Context, *GetUserRoleRequest) (*GetUserRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRole not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) AddSerial(context.Context, *AddSerialRequest) (*AddSerialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSerial not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) RemoveSerial(context.Context, *RemoveSerialRequest) (*RemoveSerialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSerial not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) GetSerial(context.Context, *GetSerialRequest) (*GetSerialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSerial not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) CreateDomainCert(context.Context, *CreateDomainCertRequest) (*CreateDomainCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDomainCert not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) DeleteDomainCert(context.Context, *DeleteDomainCertRequest) (*DeleteDomainCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomainCert not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) GetDomainCert(context.Context, *GetDomainCertRequest) (*GetDomainCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomainCert not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) GetOwnershipVoucher(context.Context, *GetOwnershipVoucherRequest) (*GetOwnershipVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOwnershipVoucher not implemented")
}
func (UnimplementedOwnershipVoucherServiceServer) testEmbeddedByValue() {}

// UnsafeOwnershipVoucherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OwnershipVoucherServiceServer will
// result in compilation errors.
type UnsafeOwnershipVoucherServiceServer interface {
	mustEmbedUnimplementedOwnershipVoucherServiceServer()
}

func RegisterOwnershipVoucherServiceServer(s grpc.ServiceRegistrar, srv OwnershipVoucherServiceServer) {
	// If the following call pancis, it indicates UnimplementedOwnershipVoucherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OwnershipVoucherService_ServiceDesc, srv)
}

func _OwnershipVoucherService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_AddUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).AddUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_AddUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).AddUserRole(ctx, req.(*AddUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_RemoveUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).RemoveUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_RemoveUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).RemoveUserRole(ctx, req.(*RemoveUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_GetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).GetUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_GetUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).GetUserRole(ctx, req.(*GetUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_AddSerial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSerialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).AddSerial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_AddSerial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).AddSerial(ctx, req.(*AddSerialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_RemoveSerial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSerialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).RemoveSerial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_RemoveSerial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).RemoveSerial(ctx, req.(*RemoveSerialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_GetSerial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSerialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).GetSerial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_GetSerial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).GetSerial(ctx, req.(*GetSerialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_CreateDomainCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).CreateDomainCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_CreateDomainCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).CreateDomainCert(ctx, req.(*CreateDomainCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_DeleteDomainCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).DeleteDomainCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_DeleteDomainCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).DeleteDomainCert(ctx, req.(*DeleteDomainCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_GetDomainCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).GetDomainCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_GetDomainCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).GetDomainCert(ctx, req.(*GetDomainCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwnershipVoucherService_GetOwnershipVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOwnershipVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnershipVoucherServiceServer).GetOwnershipVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwnershipVoucherService_GetOwnershipVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnershipVoucherServiceServer).GetOwnershipVoucher(ctx, req.(*GetOwnershipVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OwnershipVoucherService_ServiceDesc is the grpc.ServiceDesc for OwnershipVoucherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OwnershipVoucherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ovgs.v1.OwnershipVoucherService",
	HandlerType: (*OwnershipVoucherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _OwnershipVoucherService_CreateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _OwnershipVoucherService_DeleteGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _OwnershipVoucherService_GetGroup_Handler,
		},
		{
			MethodName: "AddUserRole",
			Handler:    _OwnershipVoucherService_AddUserRole_Handler,
		},
		{
			MethodName: "RemoveUserRole",
			Handler:    _OwnershipVoucherService_RemoveUserRole_Handler,
		},
		{
			MethodName: "GetUserRole",
			Handler:    _OwnershipVoucherService_GetUserRole_Handler,
		},
		{
			MethodName: "AddSerial",
			Handler:    _OwnershipVoucherService_AddSerial_Handler,
		},
		{
			MethodName: "RemoveSerial",
			Handler:    _OwnershipVoucherService_RemoveSerial_Handler,
		},
		{
			MethodName: "GetSerial",
			Handler:    _OwnershipVoucherService_GetSerial_Handler,
		},
		{
			MethodName: "CreateDomainCert",
			Handler:    _OwnershipVoucherService_CreateDomainCert_Handler,
		},
		{
			MethodName: "DeleteDomainCert",
			Handler:    _OwnershipVoucherService_DeleteDomainCert_Handler,
		},
		{
			MethodName: "GetDomainCert",
			Handler:    _OwnershipVoucherService_GetDomainCert_Handler,
		},
		{
			MethodName: "GetOwnershipVoucher",
			Handler:    _OwnershipVoucherService_GetOwnershipVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openconfig/ovgs/ovgs.proto",
}
