// Copyright (c) 2023 Arista Networks, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ovgs.proto

package ovgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	// Internal to the service, used by the vendor to invoke support related operations
	// Read write to everything
	UserRole_USER_ROLE_SUPPORT UserRole = 1
	// Read write to everything
	UserRole_USER_ROLE_ADMIN UserRole = 2
	// Read everything, write certs and serials
	UserRole_USER_ROLE_ASSIGNER UserRole = 3
	// Read only
	UserRole_USER_ROLE_REQUESTOR UserRole = 4
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_SUPPORT",
		2: "USER_ROLE_ADMIN",
		3: "USER_ROLE_ASSIGNER",
		4: "USER_ROLE_REQUESTOR",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_SUPPORT":     1,
		"USER_ROLE_ADMIN":       2,
		"USER_ROLE_ASSIGNER":    3,
		"USER_ROLE_REQUESTOR":   4,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ovgs_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_ovgs_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{0}
}

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	// USER represents a user account, tied to their identity, as specified by the
	// authentication mechanism provided
	AccountType_ACCOUNT_TYPE_USER AccountType = 1
	// SERVICE_ACCOUNT provides an identity that is not tied to a human/user and is intended for
	// programmatic access from any app/service (say the bootstrap server) to the ovgs service
	// This can typically be achieved by creating service accounts (with some name), and issuing
	// long lived tokens against that service account name
	AccountType_ACCOUNT_TYPE_SERVICE_ACCOUNT AccountType = 2
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_USER",
		2: "ACCOUNT_TYPE_SERVICE_ACCOUNT",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED":     0,
		"ACCOUNT_TYPE_USER":            1,
		"ACCOUNT_TYPE_SERVICE_ACCOUNT": 2,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_ovgs_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_ovgs_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{1}
}

// User/service accounts are assumed to have been created by some mechanism outside of
// ovgs, but are known to it. This service only deals with the assignment of roles to
// these existing user/service accounts.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username or Service Account name.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// User account type
	UserType AccountType `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=ovgs.v1.AccountType" json:"user_type,omitempty"`
	// org_id = "org-" + org name. A calling User will know their org_id.
	OrgId string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Role of the user, one of ADMIN, ASSIGNER or REQUESTOR.
	UserRole      UserRole `protobuf:"varint,4,opt,name=user_role,json=userRole,proto3,enum=ovgs.v1.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_ovgs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetUserType() AccountType {
	if x != nil {
		return x.UserType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *User) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *User) GetUserRole() UserRole {
	if x != nil {
		return x.UserRole
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

// A component uniquely identifies a part which can be queried by this service
type Component struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ien is the vendor's IANA Enterprise Number.
	Ien           string `protobuf:"bytes,1,opt,name=ien,proto3" json:"ien,omitempty"`
	SerialNumber  string `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_ovgs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{1}
}

func (x *Component) GetIen() string {
	if x != nil {
		return x.Ien
	}
	return ""
}

func (x *Component) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

// TpmInfo conveys the details about the Trusted Platform Module (TPM) on the component
type TpmInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ASN.1 DER encoded public component of the TPM's Endorsement Key (if applicable).
	// This is mainly for TPM 1.2 devices.
	EndorsementKey []byte `protobuf:"bytes,1,opt,name=endorsement_key,json=endorsementKey,proto3" json:"endorsement_key,omitempty"`
	// The ASN.1 DER encoded public component of the Platform Primary Key (if applicable)
	// This is mainly for TPM 2.0 devices with no IDevID support.
	PlatformPrimaryKey []byte `protobuf:"bytes,2,opt,name=platform_primary_key,json=platformPrimaryKey,proto3" json:"platform_primary_key,omitempty"`
	// The DER encoded X.509 certificate vouching for the authenticity of the endorsement
	// key (if applicable).
	// This is mainly for TPM 2.0 devices with IDevID support.
	EkCertificate []byte `protobuf:"bytes,3,opt,name=ek_certificate,json=ekCertificate,proto3" json:"ek_certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TpmInfo) Reset() {
	*x = TpmInfo{}
	mi := &file_ovgs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpmInfo) ProtoMessage() {}

func (x *TpmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpmInfo.ProtoReflect.Descriptor instead.
func (*TpmInfo) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{2}
}

func (x *TpmInfo) GetEndorsementKey() []byte {
	if x != nil {
		return x.EndorsementKey
	}
	return nil
}

func (x *TpmInfo) GetPlatformPrimaryKey() []byte {
	if x != nil {
		return x.PlatformPrimaryKey
	}
	return nil
}

func (x *TpmInfo) GetEkCertificate() []byte {
	if x != nil {
		return x.EkCertificate
	}
	return nil
}

// The group heirarchy is rooted at the root group (group_id = org_id)
type CreateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent group ID, it could be org ID or a group ID.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Description of the group.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_ovgs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_ovgs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_ovgs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group id
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// list of certificate IDs associated with the group.  Each ID is specific
	// to the given certificate and this group.
	CertIds []string `protobuf:"bytes,2,rep,name=cert_ids,json=certIds,proto3" json:"cert_ids,omitempty"`
	// list of components in the group.
	Components []*Component `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	// list of users in the group.
	Users []*User `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	// list of group ids that are children of this group.
	ChildGroupIds []string `protobuf:"bytes,5,rep,name=child_group_ids,json=childGroupIds,proto3" json:"child_group_ids,omitempty"`
	// Description of group
	Description   string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_ovgs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupResponse) GetCertIds() []string {
	if x != nil {
		return x.CertIds
	}
	return nil
}

func (x *GetGroupResponse) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *GetGroupResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetGroupResponse) GetChildGroupIds() []string {
	if x != nil {
		return x.ChildGroupIds
	}
	return nil
}

func (x *GetGroupResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_ovgs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_ovgs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{8}
}

// Roles are assigned to users in the context of a group, giving them
// certain permissions (as defined by that role) within the group.
// A User can assign a role to another User only if it has a role with
// equal or higher privileges. The following assignments are possible -
// Caller Role    |   Assignable Roles
//
//	ADMIN         |    ADMIN, ASSIGNER, REQUESTOR
//	ASSIGNER      |    ASSIGNER, REQUESTOR
//	REQUESTOR     |    NA (cannot assign roles)
type AddUserRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username or service account name
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// user account type
	UserType AccountType `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=ovgs.v1.AccountType" json:"user_type,omitempty"`
	// org_id = "org-" + org name
	OrgId string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Group id to assign to the user.  Must be set.
	GroupId string `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// role of the user, one of ADMIN, ASSIGNER or REQUESTOR.
	UserRole      UserRole `protobuf:"varint,5,opt,name=user_role,json=userRole,proto3,enum=ovgs.v1.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRoleRequest) Reset() {
	*x = AddUserRoleRequest{}
	mi := &file_ovgs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRoleRequest) ProtoMessage() {}

func (x *AddUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRoleRequest.ProtoReflect.Descriptor instead.
func (*AddUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{9}
}

func (x *AddUserRoleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUserRoleRequest) GetUserType() AccountType {
	if x != nil {
		return x.UserType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *AddUserRoleRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AddUserRoleRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddUserRoleRequest) GetUserRole() UserRole {
	if x != nil {
		return x.UserRole
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

type AddUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRoleResponse) Reset() {
	*x = AddUserRoleResponse{}
	mi := &file_ovgs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRoleResponse) ProtoMessage() {}

func (x *AddUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRoleResponse.ProtoReflect.Descriptor instead.
func (*AddUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{10}
}

type RemoveUserRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username or service account name
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// user account type
	UserType AccountType `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=ovgs.v1.AccountType" json:"user_type,omitempty"`
	// org_id = "org-" + org name
	OrgId         string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId       string `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRoleRequest) Reset() {
	*x = RemoveUserRoleRequest{}
	mi := &file_ovgs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRoleRequest) ProtoMessage() {}

func (x *RemoveUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveUserRoleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RemoveUserRoleRequest) GetUserType() AccountType {
	if x != nil {
		return x.UserType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *RemoveUserRoleRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RemoveUserRoleRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type RemoveUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRoleResponse) Reset() {
	*x = RemoveUserRoleResponse{}
	mi := &file_ovgs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRoleResponse) ProtoMessage() {}

func (x *RemoveUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRoleResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{12}
}

type GetUserRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username or service account name
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// user type
	UserType AccountType `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=ovgs.v1.AccountType" json:"user_type,omitempty"`
	// org_id = "org-" + org name
	OrgId         string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoleRequest) Reset() {
	*x = GetUserRoleRequest{}
	mi := &file_ovgs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoleRequest) ProtoMessage() {}

func (x *GetUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoleRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRoleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserRoleRequest) GetUserType() AccountType {
	if x != nil {
		return x.UserType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *GetUserRoleRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type GetUserRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mapping from a group to user's role in that group
	Groups        map[string]UserRole `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=ovgs.v1.UserRole"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoleResponse) Reset() {
	*x = GetUserRoleResponse{}
	mi := &file_ovgs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoleResponse) ProtoMessage() {}

func (x *GetUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoleResponse.ProtoReflect.Descriptor instead.
func (*GetUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserRoleResponse) GetGroups() map[string]UserRole {
	if x != nil {
		return x.Groups
	}
	return nil
}

// Domain certs contain PDCs assigned to groups.
type CreateDomainCertRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CertificateDer   []byte                 `protobuf:"bytes,2,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	RevocationChecks bool                   `protobuf:"varint,3,opt,name=revocation_checks,json=revocationChecks,proto3" json:"revocation_checks,omitempty"`
	ExpiryTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateDomainCertRequest) Reset() {
	*x = CreateDomainCertRequest{}
	mi := &file_ovgs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainCertRequest) ProtoMessage() {}

func (x *CreateDomainCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainCertRequest.ProtoReflect.Descriptor instead.
func (*CreateDomainCertRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{15}
}

func (x *CreateDomainCertRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateDomainCertRequest) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *CreateDomainCertRequest) GetRevocationChecks() bool {
	if x != nil {
		return x.RevocationChecks
	}
	return false
}

func (x *CreateDomainCertRequest) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

type CreateDomainCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertId        string                 `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDomainCertResponse) Reset() {
	*x = CreateDomainCertResponse{}
	mi := &file_ovgs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainCertResponse) ProtoMessage() {}

func (x *CreateDomainCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainCertResponse.ProtoReflect.Descriptor instead.
func (*CreateDomainCertResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{16}
}

func (x *CreateDomainCertResponse) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

type GetDomainCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertId        string                 `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainCertRequest) Reset() {
	*x = GetDomainCertRequest{}
	mi := &file_ovgs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainCertRequest) ProtoMessage() {}

func (x *GetDomainCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainCertRequest.ProtoReflect.Descriptor instead.
func (*GetDomainCertRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{17}
}

func (x *GetDomainCertRequest) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

type GetDomainCertResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CertId           string                 `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	GroupId          string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CertificateDer   []byte                 `protobuf:"bytes,3,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	RevocationChecks bool                   `protobuf:"varint,4,opt,name=revocation_checks,json=revocationChecks,proto3" json:"revocation_checks,omitempty"`
	ExpiryTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDomainCertResponse) Reset() {
	*x = GetDomainCertResponse{}
	mi := &file_ovgs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainCertResponse) ProtoMessage() {}

func (x *GetDomainCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainCertResponse.ProtoReflect.Descriptor instead.
func (*GetDomainCertResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{18}
}

func (x *GetDomainCertResponse) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

func (x *GetDomainCertResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetDomainCertResponse) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *GetDomainCertResponse) GetRevocationChecks() bool {
	if x != nil {
		return x.RevocationChecks
	}
	return false
}

func (x *GetDomainCertResponse) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

type DeleteDomainCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertId        string                 `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainCertRequest) Reset() {
	*x = DeleteDomainCertRequest{}
	mi := &file_ovgs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainCertRequest) ProtoMessage() {}

func (x *DeleteDomainCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainCertRequest.ProtoReflect.Descriptor instead.
func (*DeleteDomainCertRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteDomainCertRequest) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

type DeleteDomainCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainCertResponse) Reset() {
	*x = DeleteDomainCertResponse{}
	mi := &file_ovgs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainCertResponse) ProtoMessage() {}

func (x *DeleteDomainCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainCertResponse.ProtoReflect.Descriptor instead.
func (*DeleteDomainCertResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{20}
}

type AddSerialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSerialRequest) Reset() {
	*x = AddSerialRequest{}
	mi := &file_ovgs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSerialRequest) ProtoMessage() {}

func (x *AddSerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSerialRequest.ProtoReflect.Descriptor instead.
func (*AddSerialRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{21}
}

func (x *AddSerialRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *AddSerialRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type AddSerialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSerialResponse) Reset() {
	*x = AddSerialResponse{}
	mi := &file_ovgs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSerialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSerialResponse) ProtoMessage() {}

func (x *AddSerialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSerialResponse.ProtoReflect.Descriptor instead.
func (*AddSerialResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{22}
}

type RemoveSerialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSerialRequest) Reset() {
	*x = RemoveSerialRequest{}
	mi := &file_ovgs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSerialRequest) ProtoMessage() {}

func (x *RemoveSerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSerialRequest.ProtoReflect.Descriptor instead.
func (*RemoveSerialRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveSerialRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *RemoveSerialRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type RemoveSerialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSerialResponse) Reset() {
	*x = RemoveSerialResponse{}
	mi := &file_ovgs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSerialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSerialResponse) ProtoMessage() {}

func (x *RemoveSerialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSerialResponse.ProtoReflect.Descriptor instead.
func (*RemoveSerialResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{24}
}

type GetSerialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     *Component             `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSerialRequest) Reset() {
	*x = GetSerialRequest{}
	mi := &file_ovgs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSerialRequest) ProtoMessage() {}

func (x *GetSerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSerialRequest.ProtoReflect.Descriptor instead.
func (*GetSerialRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{25}
}

func (x *GetSerialRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

type GetSerialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Use tpm_info instead.
	// TPM's (if applicable) endorsement key in ASN.1 DER encoded format
	//
	// Deprecated: Marked as deprecated in ovgs.proto.
	PublicKeyDer []byte `protobuf:"bytes,1,opt,name=public_key_der,json=publicKeyDer,proto3" json:"public_key_der,omitempty"`
	// List of groups the serial number belongs to.
	GroupIds []string `protobuf:"bytes,2,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	// SKU mac address
	MacAddr string `protobuf:"bytes,3,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	// SKU/Hardware model name
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// TPM related info
	TpmInfo       *TpmInfo `protobuf:"bytes,5,opt,name=tpm_info,json=tpmInfo,proto3" json:"tpm_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSerialResponse) Reset() {
	*x = GetSerialResponse{}
	mi := &file_ovgs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSerialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSerialResponse) ProtoMessage() {}

func (x *GetSerialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSerialResponse.ProtoReflect.Descriptor instead.
func (*GetSerialResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{26}
}

// Deprecated: Marked as deprecated in ovgs.proto.
func (x *GetSerialResponse) GetPublicKeyDer() []byte {
	if x != nil {
		return x.PublicKeyDer
	}
	return nil
}

func (x *GetSerialResponse) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *GetSerialResponse) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *GetSerialResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetSerialResponse) GetTpmInfo() *TpmInfo {
	if x != nil {
		return x.TpmInfo
	}
	return nil
}

type GetOwnershipVoucherRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serial number for the part to fetch OV.
	Component *Component `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// Certificate ID to use for OV.
	CertId string `protobuf:"bytes,2,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	// Lifetime of the OV.
	Lifetime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnershipVoucherRequest) Reset() {
	*x = GetOwnershipVoucherRequest{}
	mi := &file_ovgs_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnershipVoucherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnershipVoucherRequest) ProtoMessage() {}

func (x *GetOwnershipVoucherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnershipVoucherRequest.ProtoReflect.Descriptor instead.
func (*GetOwnershipVoucherRequest) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{27}
}

func (x *GetOwnershipVoucherRequest) GetComponent() *Component {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *GetOwnershipVoucherRequest) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

func (x *GetOwnershipVoucherRequest) GetLifetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

type GetOwnershipVoucherResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Voucher in binary CMS format (rfc5652)
	VoucherCms []byte `protobuf:"bytes,1,opt,name=voucher_cms,json=voucherCms,proto3" json:"voucher_cms,omitempty"`
	// Deprecated: Use tpm_info instead.
	// TPM's (if applicable) endorsement key in ASN.1 DER encoded format
	//
	// Deprecated: Marked as deprecated in ovgs.proto.
	PublicKeyDer []byte `protobuf:"bytes,2,opt,name=public_key_der,json=publicKeyDer,proto3" json:"public_key_der,omitempty"`
	// TPM related info
	TpmInfo       *TpmInfo `protobuf:"bytes,3,opt,name=tpm_info,json=tpmInfo,proto3" json:"tpm_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnershipVoucherResponse) Reset() {
	*x = GetOwnershipVoucherResponse{}
	mi := &file_ovgs_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnershipVoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnershipVoucherResponse) ProtoMessage() {}

func (x *GetOwnershipVoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ovgs_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnershipVoucherResponse.ProtoReflect.Descriptor instead.
func (*GetOwnershipVoucherResponse) Descriptor() ([]byte, []int) {
	return file_ovgs_proto_rawDescGZIP(), []int{28}
}

func (x *GetOwnershipVoucherResponse) GetVoucherCms() []byte {
	if x != nil {
		return x.VoucherCms
	}
	return nil
}

// Deprecated: Marked as deprecated in ovgs.proto.
func (x *GetOwnershipVoucherResponse) GetPublicKeyDer() []byte {
	if x != nil {
		return x.PublicKeyDer
	}
	return nil
}

func (x *GetOwnershipVoucherResponse) GetTpmInfo() *TpmInfo {
	if x != nil {
		return x.TpmInfo
	}
	return nil
}

var File_ovgs_proto protoreflect.FileDescriptor

const file_ovgs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ovgs.proto\x12\aovgs.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x121\n" +
	"\tuser_type\x18\x02 \x01(\x0e2\x14.ovgs.v1.AccountTypeR\buserType\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12.\n" +
	"\tuser_role\x18\x04 \x01(\x0e2\x11.ovgs.v1.UserRoleR\buserRole\"B\n" +
	"\tComponent\x12\x10\n" +
	"\x03ien\x18\x01 \x01(\tR\x03ien\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\"\x8b\x01\n" +
	"\aTpmInfo\x12'\n" +
	"\x0fendorsement_key\x18\x01 \x01(\fR\x0eendorsementKey\x120\n" +
	"\x14platform_primary_key\x18\x02 \x01(\fR\x12platformPrimaryKey\x12%\n" +
	"\x0eek_certificate\x18\x03 \x01(\fR\rekCertificate\"N\n" +
	"\x12CreateGroupRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"0\n" +
	"\x13CreateGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\",\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\xeb\x01\n" +
	"\x10GetGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x19\n" +
	"\bcert_ids\x18\x02 \x03(\tR\acertIds\x122\n" +
	"\n" +
	"components\x18\x03 \x03(\v2\x12.ovgs.v1.ComponentR\n" +
	"components\x12#\n" +
	"\x05users\x18\x04 \x03(\v2\r.ovgs.v1.UserR\x05users\x12&\n" +
	"\x0fchild_group_ids\x18\x05 \x03(\tR\rchildGroupIds\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"/\n" +
	"\x12DeleteGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x15\n" +
	"\x13DeleteGroupResponse\"\xc5\x01\n" +
	"\x12AddUserRoleRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x121\n" +
	"\tuser_type\x18\x02 \x01(\x0e2\x14.ovgs.v1.AccountTypeR\buserType\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12.\n" +
	"\tuser_role\x18\x05 \x01(\x0e2\x11.ovgs.v1.UserRoleR\buserRole\"\x15\n" +
	"\x13AddUserRoleResponse\"\x98\x01\n" +
	"\x15RemoveUserRoleRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x121\n" +
	"\tuser_type\x18\x02 \x01(\x0e2\x14.ovgs.v1.AccountTypeR\buserType\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\"\x18\n" +
	"\x16RemoveUserRoleResponse\"z\n" +
	"\x12GetUserRoleRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x121\n" +
	"\tuser_type\x18\x02 \x01(\x0e2\x14.ovgs.v1.AccountTypeR\buserType\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\"\xa5\x01\n" +
	"\x13GetUserRoleResponse\x12@\n" +
	"\x06groups\x18\x01 \x03(\v2(.ovgs.v1.GetUserRoleResponse.GroupsEntryR\x06groups\x1aL\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\x0e2\x11.ovgs.v1.UserRoleR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x17CreateDomainCertRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12'\n" +
	"\x0fcertificate_der\x18\x02 \x01(\fR\x0ecertificateDer\x12+\n" +
	"\x11revocation_checks\x18\x03 \x01(\bR\x10revocationChecks\x12;\n" +
	"\vexpiry_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryTime\"3\n" +
	"\x18CreateDomainCertResponse\x12\x17\n" +
	"\acert_id\x18\x01 \x01(\tR\x06certId\"/\n" +
	"\x14GetDomainCertRequest\x12\x17\n" +
	"\acert_id\x18\x01 \x01(\tR\x06certId\"\xde\x01\n" +
	"\x15GetDomainCertResponse\x12\x17\n" +
	"\acert_id\x18\x01 \x01(\tR\x06certId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12'\n" +
	"\x0fcertificate_der\x18\x03 \x01(\fR\x0ecertificateDer\x12+\n" +
	"\x11revocation_checks\x18\x04 \x01(\bR\x10revocationChecks\x12;\n" +
	"\vexpiry_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryTime\"2\n" +
	"\x17DeleteDomainCertRequest\x12\x17\n" +
	"\acert_id\x18\x01 \x01(\tR\x06certId\"\x1a\n" +
	"\x18DeleteDomainCertResponse\"_\n" +
	"\x10AddSerialRequest\x120\n" +
	"\tcomponent\x18\x01 \x01(\v2\x12.ovgs.v1.ComponentR\tcomponent\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"\x13\n" +
	"\x11AddSerialResponse\"b\n" +
	"\x13RemoveSerialRequest\x120\n" +
	"\tcomponent\x18\x01 \x01(\v2\x12.ovgs.v1.ComponentR\tcomponent\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"\x16\n" +
	"\x14RemoveSerialResponse\"D\n" +
	"\x10GetSerialRequest\x120\n" +
	"\tcomponent\x18\x01 \x01(\v2\x12.ovgs.v1.ComponentR\tcomponent\"\xb8\x01\n" +
	"\x11GetSerialResponse\x12(\n" +
	"\x0epublic_key_der\x18\x01 \x01(\fB\x02\x18\x01R\fpublicKeyDer\x12\x1b\n" +
	"\tgroup_ids\x18\x02 \x03(\tR\bgroupIds\x12\x19\n" +
	"\bmac_addr\x18\x03 \x01(\tR\amacAddr\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12+\n" +
	"\btpm_info\x18\x05 \x01(\v2\x10.ovgs.v1.TpmInfoR\atpmInfo\"\x9f\x01\n" +
	"\x1aGetOwnershipVoucherRequest\x120\n" +
	"\tcomponent\x18\x01 \x01(\v2\x12.ovgs.v1.ComponentR\tcomponent\x12\x17\n" +
	"\acert_id\x18\x02 \x01(\tR\x06certId\x126\n" +
	"\blifetime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blifetime\"\x95\x01\n" +
	"\x1bGetOwnershipVoucherResponse\x12\x1f\n" +
	"\vvoucher_cms\x18\x01 \x01(\fR\n" +
	"voucherCms\x12(\n" +
	"\x0epublic_key_der\x18\x02 \x01(\fB\x02\x18\x01R\fpublicKeyDer\x12+\n" +
	"\btpm_info\x18\x03 \x01(\v2\x10.ovgs.v1.TpmInfoR\atpmInfo*\x82\x01\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11USER_ROLE_SUPPORT\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02\x12\x16\n" +
	"\x12USER_ROLE_ASSIGNER\x10\x03\x12\x17\n" +
	"\x13USER_ROLE_REQUESTOR\x10\x04*d\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCOUNT_TYPE_USER\x10\x01\x12 \n" +
	"\x1cACCOUNT_TYPE_SERVICE_ACCOUNT\x10\x022\x8e\b\n" +
	"\x17OwnershipVoucherService\x12H\n" +
	"\vCreateGroup\x12\x1b.ovgs.v1.CreateGroupRequest\x1a\x1c.ovgs.v1.CreateGroupResponse\x12H\n" +
	"\vDeleteGroup\x12\x1b.ovgs.v1.DeleteGroupRequest\x1a\x1c.ovgs.v1.DeleteGroupResponse\x12?\n" +
	"\bGetGroup\x12\x18.ovgs.v1.GetGroupRequest\x1a\x19.ovgs.v1.GetGroupResponse\x12H\n" +
	"\vAddUserRole\x12\x1b.ovgs.v1.AddUserRoleRequest\x1a\x1c.ovgs.v1.AddUserRoleResponse\x12Q\n" +
	"\x0eRemoveUserRole\x12\x1e.ovgs.v1.RemoveUserRoleRequest\x1a\x1f.ovgs.v1.RemoveUserRoleResponse\x12H\n" +
	"\vGetUserRole\x12\x1b.ovgs.v1.GetUserRoleRequest\x1a\x1c.ovgs.v1.GetUserRoleResponse\x12B\n" +
	"\tAddSerial\x12\x19.ovgs.v1.AddSerialRequest\x1a\x1a.ovgs.v1.AddSerialResponse\x12K\n" +
	"\fRemoveSerial\x12\x1c.ovgs.v1.RemoveSerialRequest\x1a\x1d.ovgs.v1.RemoveSerialResponse\x12B\n" +
	"\tGetSerial\x12\x19.ovgs.v1.GetSerialRequest\x1a\x1a.ovgs.v1.GetSerialResponse\x12W\n" +
	"\x10CreateDomainCert\x12 .ovgs.v1.CreateDomainCertRequest\x1a!.ovgs.v1.CreateDomainCertResponse\x12W\n" +
	"\x10DeleteDomainCert\x12 .ovgs.v1.DeleteDomainCertRequest\x1a!.ovgs.v1.DeleteDomainCertResponse\x12N\n" +
	"\rGetDomainCert\x12\x1d.ovgs.v1.GetDomainCertRequest\x1a\x1e.ovgs.v1.GetDomainCertResponse\x12`\n" +
	"\x13GetOwnershipVoucher\x12#.ovgs.v1.GetOwnershipVoucherRequest\x1a$.ovgs.v1.GetOwnershipVoucherResponseB7Z5github.com/aristanetworks/ownership-voucher-grpc/ovgsb\x06proto3"

var (
	file_ovgs_proto_rawDescOnce sync.Once
	file_ovgs_proto_rawDescData []byte
)

func file_ovgs_proto_rawDescGZIP() []byte {
	file_ovgs_proto_rawDescOnce.Do(func() {
		file_ovgs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ovgs_proto_rawDesc), len(file_ovgs_proto_rawDesc)))
	})
	return file_ovgs_proto_rawDescData
}

var file_ovgs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ovgs_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_ovgs_proto_goTypes = []any{
	(UserRole)(0),                       // 0: ovgs.v1.UserRole
	(AccountType)(0),                    // 1: ovgs.v1.AccountType
	(*User)(nil),                        // 2: ovgs.v1.User
	(*Component)(nil),                   // 3: ovgs.v1.Component
	(*TpmInfo)(nil),                     // 4: ovgs.v1.TpmInfo
	(*CreateGroupRequest)(nil),          // 5: ovgs.v1.CreateGroupRequest
	(*CreateGroupResponse)(nil),         // 6: ovgs.v1.CreateGroupResponse
	(*GetGroupRequest)(nil),             // 7: ovgs.v1.GetGroupRequest
	(*GetGroupResponse)(nil),            // 8: ovgs.v1.GetGroupResponse
	(*DeleteGroupRequest)(nil),          // 9: ovgs.v1.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),         // 10: ovgs.v1.DeleteGroupResponse
	(*AddUserRoleRequest)(nil),          // 11: ovgs.v1.AddUserRoleRequest
	(*AddUserRoleResponse)(nil),         // 12: ovgs.v1.AddUserRoleResponse
	(*RemoveUserRoleRequest)(nil),       // 13: ovgs.v1.RemoveUserRoleRequest
	(*RemoveUserRoleResponse)(nil),      // 14: ovgs.v1.RemoveUserRoleResponse
	(*GetUserRoleRequest)(nil),          // 15: ovgs.v1.GetUserRoleRequest
	(*GetUserRoleResponse)(nil),         // 16: ovgs.v1.GetUserRoleResponse
	(*CreateDomainCertRequest)(nil),     // 17: ovgs.v1.CreateDomainCertRequest
	(*CreateDomainCertResponse)(nil),    // 18: ovgs.v1.CreateDomainCertResponse
	(*GetDomainCertRequest)(nil),        // 19: ovgs.v1.GetDomainCertRequest
	(*GetDomainCertResponse)(nil),       // 20: ovgs.v1.GetDomainCertResponse
	(*DeleteDomainCertRequest)(nil),     // 21: ovgs.v1.DeleteDomainCertRequest
	(*DeleteDomainCertResponse)(nil),    // 22: ovgs.v1.DeleteDomainCertResponse
	(*AddSerialRequest)(nil),            // 23: ovgs.v1.AddSerialRequest
	(*AddSerialResponse)(nil),           // 24: ovgs.v1.AddSerialResponse
	(*RemoveSerialRequest)(nil),         // 25: ovgs.v1.RemoveSerialRequest
	(*RemoveSerialResponse)(nil),        // 26: ovgs.v1.RemoveSerialResponse
	(*GetSerialRequest)(nil),            // 27: ovgs.v1.GetSerialRequest
	(*GetSerialResponse)(nil),           // 28: ovgs.v1.GetSerialResponse
	(*GetOwnershipVoucherRequest)(nil),  // 29: ovgs.v1.GetOwnershipVoucherRequest
	(*GetOwnershipVoucherResponse)(nil), // 30: ovgs.v1.GetOwnershipVoucherResponse
	nil,                                 // 31: ovgs.v1.GetUserRoleResponse.GroupsEntry
	(*timestamppb.Timestamp)(nil),       // 32: google.protobuf.Timestamp
}
var file_ovgs_proto_depIdxs = []int32{
	1,  // 0: ovgs.v1.User.user_type:type_name -> ovgs.v1.AccountType
	0,  // 1: ovgs.v1.User.user_role:type_name -> ovgs.v1.UserRole
	3,  // 2: ovgs.v1.GetGroupResponse.components:type_name -> ovgs.v1.Component
	2,  // 3: ovgs.v1.GetGroupResponse.users:type_name -> ovgs.v1.User
	1,  // 4: ovgs.v1.AddUserRoleRequest.user_type:type_name -> ovgs.v1.AccountType
	0,  // 5: ovgs.v1.AddUserRoleRequest.user_role:type_name -> ovgs.v1.UserRole
	1,  // 6: ovgs.v1.RemoveUserRoleRequest.user_type:type_name -> ovgs.v1.AccountType
	1,  // 7: ovgs.v1.GetUserRoleRequest.user_type:type_name -> ovgs.v1.AccountType
	31, // 8: ovgs.v1.GetUserRoleResponse.groups:type_name -> ovgs.v1.GetUserRoleResponse.GroupsEntry
	32, // 9: ovgs.v1.CreateDomainCertRequest.expiry_time:type_name -> google.protobuf.Timestamp
	32, // 10: ovgs.v1.GetDomainCertResponse.expiry_time:type_name -> google.protobuf.Timestamp
	3,  // 11: ovgs.v1.AddSerialRequest.component:type_name -> ovgs.v1.Component
	3,  // 12: ovgs.v1.RemoveSerialRequest.component:type_name -> ovgs.v1.Component
	3,  // 13: ovgs.v1.GetSerialRequest.component:type_name -> ovgs.v1.Component
	4,  // 14: ovgs.v1.GetSerialResponse.tpm_info:type_name -> ovgs.v1.TpmInfo
	3,  // 15: ovgs.v1.GetOwnershipVoucherRequest.component:type_name -> ovgs.v1.Component
	32, // 16: ovgs.v1.GetOwnershipVoucherRequest.lifetime:type_name -> google.protobuf.Timestamp
	4,  // 17: ovgs.v1.GetOwnershipVoucherResponse.tpm_info:type_name -> ovgs.v1.TpmInfo
	0,  // 18: ovgs.v1.GetUserRoleResponse.GroupsEntry.value:type_name -> ovgs.v1.UserRole
	5,  // 19: ovgs.v1.OwnershipVoucherService.CreateGroup:input_type -> ovgs.v1.CreateGroupRequest
	9,  // 20: ovgs.v1.OwnershipVoucherService.DeleteGroup:input_type -> ovgs.v1.DeleteGroupRequest
	7,  // 21: ovgs.v1.OwnershipVoucherService.GetGroup:input_type -> ovgs.v1.GetGroupRequest
	11, // 22: ovgs.v1.OwnershipVoucherService.AddUserRole:input_type -> ovgs.v1.AddUserRoleRequest
	13, // 23: ovgs.v1.OwnershipVoucherService.RemoveUserRole:input_type -> ovgs.v1.RemoveUserRoleRequest
	15, // 24: ovgs.v1.OwnershipVoucherService.GetUserRole:input_type -> ovgs.v1.GetUserRoleRequest
	23, // 25: ovgs.v1.OwnershipVoucherService.AddSerial:input_type -> ovgs.v1.AddSerialRequest
	25, // 26: ovgs.v1.OwnershipVoucherService.RemoveSerial:input_type -> ovgs.v1.RemoveSerialRequest
	27, // 27: ovgs.v1.OwnershipVoucherService.GetSerial:input_type -> ovgs.v1.GetSerialRequest
	17, // 28: ovgs.v1.OwnershipVoucherService.CreateDomainCert:input_type -> ovgs.v1.CreateDomainCertRequest
	21, // 29: ovgs.v1.OwnershipVoucherService.DeleteDomainCert:input_type -> ovgs.v1.DeleteDomainCertRequest
	19, // 30: ovgs.v1.OwnershipVoucherService.GetDomainCert:input_type -> ovgs.v1.GetDomainCertRequest
	29, // 31: ovgs.v1.OwnershipVoucherService.GetOwnershipVoucher:input_type -> ovgs.v1.GetOwnershipVoucherRequest
	6,  // 32: ovgs.v1.OwnershipVoucherService.CreateGroup:output_type -> ovgs.v1.CreateGroupResponse
	10, // 33: ovgs.v1.OwnershipVoucherService.DeleteGroup:output_type -> ovgs.v1.DeleteGroupResponse
	8,  // 34: ovgs.v1.OwnershipVoucherService.GetGroup:output_type -> ovgs.v1.GetGroupResponse
	12, // 35: ovgs.v1.OwnershipVoucherService.AddUserRole:output_type -> ovgs.v1.AddUserRoleResponse
	14, // 36: ovgs.v1.OwnershipVoucherService.RemoveUserRole:output_type -> ovgs.v1.RemoveUserRoleResponse
	16, // 37: ovgs.v1.OwnershipVoucherService.GetUserRole:output_type -> ovgs.v1.GetUserRoleResponse
	24, // 38: ovgs.v1.OwnershipVoucherService.AddSerial:output_type -> ovgs.v1.AddSerialResponse
	26, // 39: ovgs.v1.OwnershipVoucherService.RemoveSerial:output_type -> ovgs.v1.RemoveSerialResponse
	28, // 40: ovgs.v1.OwnershipVoucherService.GetSerial:output_type -> ovgs.v1.GetSerialResponse
	18, // 41: ovgs.v1.OwnershipVoucherService.CreateDomainCert:output_type -> ovgs.v1.CreateDomainCertResponse
	22, // 42: ovgs.v1.OwnershipVoucherService.DeleteDomainCert:output_type -> ovgs.v1.DeleteDomainCertResponse
	20, // 43: ovgs.v1.OwnershipVoucherService.GetDomainCert:output_type -> ovgs.v1.GetDomainCertResponse
	30, // 44: ovgs.v1.OwnershipVoucherService.GetOwnershipVoucher:output_type -> ovgs.v1.GetOwnershipVoucherResponse
	32, // [32:45] is the sub-list for method output_type
	19, // [19:32] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_ovgs_proto_init() }
func file_ovgs_proto_init() {
	if File_ovgs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ovgs_proto_rawDesc), len(file_ovgs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ovgs_proto_goTypes,
		DependencyIndexes: file_ovgs_proto_depIdxs,
		EnumInfos:         file_ovgs_proto_enumTypes,
		MessageInfos:      file_ovgs_proto_msgTypes,
	}.Build()
	File_ovgs_proto = out.File
	file_ovgs_proto_goTypes = nil
	file_ovgs_proto_depIdxs = nil
}
